import java.util.Scanner;

public class Withdraw {

    long accountNumber;
    String password;

    Withdraw() {
        Scanner scan = new Scanner(System.in);

        while (true) {
            try {
                System.out.print("Enter your accountNumber generated by our Bank: ");
                this.accountNumber = scan.nextLong();
                scan.nextLine(); // Consume the leftover newline character
                break;
            } catch (Exception e) {
                System.out.println("Invalid input! Please enter a valid numeric account number.");
                scan.nextLine(); // Clear the invalid input
            }
        }

        while (true) {
            try {
                System.out.print("Enter password: ");
                this.password = scan.nextLine();
                if (password_checker(password)) {
                    break;
                } else {
                    System.out.println("Invalid password, Try Again!!");
                }
            } catch (Exception e) {
                System.out.println("An error occurred while entering the password. Please try again.");
            }
        }
    }

    public static boolean password_checker(String password) {
        String PasswordPattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        return password.matches(PasswordPattern);
    }
}
